name: 'Retrieve ID Token'
description: 'A GitHub Action to retrieve and log the ID token'

inputs:
  policy-evaluator-url:
    description: 'The URL of the Develocity Policy Evaluator service'
    required: true
  tenant:
    description:
      'The tenant ID configured in the Develocity Attestation Publisher service'
    required: true
  policy-scan:
    description:
      'The policy scan to evaluate, using the name configured in the Develocity
      Policy Evaluator service'
    required: true
  ignore-policies-with-labels:
    description:
      'Label sets that mark policies to be ignored. Labels must use the format
      {key}={value}. Labels may be seperated by commas or newlines. Groups of
      labels seperated by a blank line are label sets. A policy matching one or
      more label sets will not cause the action to fail even if they are
      unsatisfied.'
    required: false
  subject-type:
    description: 'The type of the package to evaluate policies against'
    required: true
  subject-namespace:
    description: 'The namespace of the package to evaluate policies against'
    required: false
  subject-name:
    description: 'The name of the package to evaluate policies against'
    required: true
  subject-version:
    description: 'The version of the package to evaluate policies against'
    required: true
  subject-digest:
    description: 'The sha256 digest of the package to evaluate policies against'
    required: true
  subject-repository-url:
    description:
      'The base repository URL of the package to evaluate policies against'
    required: true
  username:
    description:
      'The username of the Develocity Policy Evaluator user (It is recommended
      to use the GitHub Actions token instead of a username/password)'
    required: false
  password:
    description:
      'The password of the Develocity Policy Evaluator user (It is recommended
      to use the GitHub Actions token instead of a username/password)'
    required: false

runs:
  using: 'node20'
  main: '../dist/policy/index.js'
