name: 'Enforce Policies'
description:
  'A GitHub Action to enforce policies configured in a Develocity Provenance
  Governor instance.'

inputs:
  policy-evaluator-url:
    description: 'The URL of the Develocity Provenance Governor service'
    required: true
  policy-scan:
    description:
      'The policy scan to evaluate, using the name configured in the Develocity
      Provenance Governor service'
    required: true
  enforcement-point:
    description:
      'EXPERIMENTAL: The enforcement point to evaluate the scan for, using the
      name configured in the Develocity Provenance Governor service'
    required: false
  subject-type:
    description: 'The type of the package to evaluate policies against'
    required: true
  subject-namespace:
    description: 'The namespace of the package to evaluate policies against'
    required: false
  subject-name:
    description: 'The name of the package to evaluate policies against'
    required: true
  subject-version:
    description: 'The version of the package to evaluate policies against'
    required: true
  subject-digest:
    description: 'The sha256 digest of the package to evaluate policies against'
    required: true
  subject-repository-url:
    description:
      'The base repository URL of the package to evaluate policies against'
    required: true
  username:
    description:
      'The username of the Develocity Provenance Governor user (It is
      recommended to use the GitHub Actions token instead of a
      username/password)'
    required: false
  password:
    description:
      'The password of the Develocity Provenance Governor user (It is
      recommended to use the GitHub Actions token instead of a
      username/password)'
    required: false

runs:
  using: 'node20'
  main: '../dist/policy/index.js'
