# Prohibit any change to 'dist/**' on a non-release branch
name: Check Transpiled JavaScript

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  fail-on-dist-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47.0.0
        with:
          files: |
            dist/**

      - name: Print changes to dist directory
        env:
          ALL_CHANGED_FILES:
            ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - if: ${{ steps.changed-files.outputs.any_changed != 'false' }}
        run: |
          echo "The 'dist' directory is automatically updated by the release process."
          echo "It should not be updated manually in a non-release branch or a pull request."
          exit 1
